# Generated by Django 3.0.8 on 2021-02-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_categoria_post_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'get_latest_by': '-created', 'ordering': ('-created',), 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
    ]
