# Generated by Django 3.0.8 on 2021-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210309_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mp4',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='webm',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
