# Generated by Django 3.0.8 on 2021-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210309_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(related_name='extendeds', to='project.File'),
        ),
    ]
