# Generated by Django 3.0.8 on 2021-03-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210309_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='images/1245.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='webm',
            field=models.FileField(blank=True, default='videos/sd45.webm', null=True, upload_to='videos/'),
        ),
    ]
