# Generated by Django 3.0.8 on 2021-03-09 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210309_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videos/poster'),
            preserve_default=False,
        ),
    ]
