# Generated by Django 3.0.8 on 2021-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.FileField(blank=True, upload_to='videos/poster'),
        ),
    ]
